%%%%% Paramètre de la Machine: %%%%%

%%%%% Puissance nominale= 1.1 kW
%%%%% V itesse nominale=  1500 tr/min
%%%%% Vitesse maximale=  1800 tr/min 
%%%%% Couple à la vitesse nominale = 7 N.m
%%%%% Couple à la vitesse maximale = 5.8 N.m
%%%%% Courant efficace nominal = 3 A
%%%%% Tension d'alimentation=  220/380 V
%%%%% Résistance par phase = 6.2 Ohm
%%%%% Inertie = 0.002 kg.m^2 J
%%%%% Nombre de paires de pôles = 2
%%%%% Coefficient de frottement visqueux = 0.01 fr

%%%%% électrique basé sur le réglage d'état (placement de pôles optimal: Le
%%%%% pôle p3 réel égal à la valeur minimum 1/3*(1/Ton+1/Te) et deux autres pôles p1 et p2 dont les valeurs réelles et imaginaires égales au pôle réel p3).

clc
clear all
Ts=1e-5; % temps d'échantillonage
Vdc=630; % tension de bus continu
G0=1;    % gain onduleur 0.5*Vdc 
R=6.2;
% R=7.8
    p=2;
    Ld=0.34;
    Lq=0.105;
% Ld=0.48
% Lq= 0.3
% Ld = 0.515
% Lq = 0.215
%Paramètres mécaniques
        
      J=0.005; %% inertie du moteur  + inertie de l'arbre
      f=0.01;   % coefficient de frottement
    Tmeca = J/f; % Const. de temps mécanique
% 
Teq=Lq/R; % Const de temps électrique q
Ted=Ld/R;  % const de temps électrique d
Ton=0.5e-4; % Const de temps onduleur
fMLI=1/2*1/Ton; % fréquence MLI
%% Regulation
%regulateur de courant avec ksi=1
wne=3000;wne1=3000;
Kpd=(Ted*2*wne-1)*R;
Kpq=(Teq*2*wne1-1)*R;
Kiq=wne1^2*Teq*R/(Kpq);
Kid=wne^2*Ted*R/(Kpd);
%regulateur de vitesse avec ksi=1
wn=40;  
Km=(Tmeca*2*wn-1)*f;
Ti1=Km/(wn^2*Tmeca*f);
%%
lambda=4000;
alpha=0.1;
lambda_1=100000;
lambda_2=100000;
c1=10;
c2=10;

%%
W=20
c=5*sqrt(20)
%% variables Q, R, P0, x0, u0, C

i=0;

Q_e = diag ([5, 5, 0.0000001, 0.0000001, 0]);
R_e = diag ([0.2, 0.2]);
x0=[0;0;0;0;0];
P0=[0.4 0 0 0 0;
    0 0.4 0 0 0;
    0 0 0 0 0;
    0 0 0 0 0;
    0 0 0 0 0];

u0=[0;0];

C = [1 0 0 0 0;
     0 1 0 0 0];
